language: ruby
script: "bundle exec rspec spec"
env:
  - CI=true
rvm:
  - 2.3.0
  - 2.2.4
  - 2.1
  - 2.0
  - jruby-9.0.4.0
  - rbx
cache: bundler
sudo: false
matrix:
  allow_failures:
      - rvm: rbx-2
